project:
  type: website
  output-dir: docs

website:
  title: "Flooded Acreage Monitoring"
  navbar:
    title: "Flooded Acreage Monitoring"
    logo: inyo_logo.png
    left:
      - href: index.html
        text: Dashboard
      - href: about.html
        text: About
      - icon: github
        href: https://github.com/inyo-gov/flooded-acreage
    background: dark
    search: true

format:
  html:
    theme: bootstrap
    linkcolor: "#2E86AB"
    css: styles.css
    toc: false
    code-fold: true
    code-tools: true
    fig-responsive: true
    table-responsive: false
    fig-dir: figure-html
    subtitle: "Blackrock Waterfowl Management Area"
    footer: "© 2025 Inyo County, California. All rights reserved."


